name: Create Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Create release branch and bump version
        env:
          REF: ${{ github.ref }}
        run: |
          BRANCH=release/${REF:10}
          git config --local user.email "github@jexactyl.com"
          git config --local user.name "Jexactyl Releases"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          sed -i "s/    'version' => 'canary',/    'version' => '${REF:11}',/" config/app.php
          git add config/app.php
          git commit -m "New Assistant release innound!"
          git push
      - name: Create release archive
        run: |
          tar -czf assistant.tar.gz * .env.example
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.extract_changelog.outputs.version_name }}
          draft: true
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}

      - name: Upload binary
        id: upload-release-archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: assistant.tar.gz
          asset_name: assistant.tar.gz
          asset_content_type: application/gzip
