#!/bin/bash

cd /var/www/jexactyl > /dev/null 2>&1
composer install --no-dev --optimize-autoloader > /dev/null 2>&1

cd /var/www/jexactyl-assistant > /dev/null 2>&1
composer install --no-dev --optimize-autoloader > /dev/null 2>&1

clear