#!/bin/bash

apt -y install software-properties-common curl apt-transport-https ca-certificates gnupg > /dev/null 2>&1
LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php > /dev/null 2>&1
add-apt-repository ppa:redislabs/redis -y > /dev/null 2>&1
curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash > /dev/null 2>&1
apt update > /dev/null 2>&1
apt -y install php8.1 php8.1-{cli,gd,mysql,sqlite3,pdo,mbstring,tokenizer,bcmath,xml,fpm,curl,zip} mariadb-server nginx tar unzip git redis-server > /dev/null 2>&1
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer > /dev/null 2>&1