#!/bin/bash

mkdir /var/www/jexactyl > /dev/null 2>&1
cd /var/www/jexactyl > /dev/null 2>&1
curl -Lo panel.tar.gz https://github.com/jexactyl/jexactyl/releases/latest/download/panel.tar.gz > /dev/null 2>&1
tar -xzvf panel.tar.gz > /dev/null 2>&1
rm panel.tar.gz > /dev/null 2>&1
chmod -R 755 storage/* bootstrap/cache/ > /dev/null 2>&1

mkdir /var/www/jexactyl-assistant > /dev/null 2>&1
cd /var/www/jexactyl-assistant > /dev/null 2>&1
curl -Lo assistant.tar.gz https://github.com/jexactyl/assistant/releases/latest/download/assistant.tar.gz > /dev/null 2>&1
tar -xzvf assistant.tar.gz > /dev/null 2>&1
rm assistant.tar.gz > /dev/null 2>&1
chmod -R 755 storage/* bootstrap/cache/ > /dev/null 2>&1

clear